from fastapi import Depends, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlmodel import Session, select
import uuid
from dotenv import load_dotenv

# Load environment variables early
load_dotenv()

from datetime import datetime
from auth import get_user_id
from database import engine, Roadmap, Task, User, Deadline, get_session
from generator import generate_roadmap_tasks, regenerate_roadmap_tasks
from knowledge_base import KnowledgeBase
from sqlalchemy.orm import Session as ORMSession
import json

app = FastAPI()
kb = KnowledgeBase()


def ensure_kb_available(feature_name: str) -> None:
    if kb.is_available():
        return

    detail = (
        f"{feature_name} is unavailable because the knowledge base failed to initialize. "
        f"{kb.get_unavailable_reason()}"
    )
    print(f"[RAG Unavailable] {detail}")
    raise HTTPException(status_code=503, detail=detail)

# Secure Admin Dependency
def get_current_admin(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
) -> User:
    user = session.exec(select(User).where(User.id == user_id)).first()
    if not user or not user.isAdmin:
        raise HTTPException(
            status_code=403, 
            detail="Forbidden: Admin access required"
        )
    return user

# Allow frontend to talk to backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",  # Next.js dev
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def format_deliverables(deliverables):
    """Converts various deliverable formats (string list, tuple list) into the standard object format."""
    if not deliverables:
        return []
    
    formatted = []
    for d in deliverables:
        if isinstance(d, str):
            formatted.append({"title": d, "completed": False, "completedAt": None})
        elif isinstance(d, (list, tuple)) and len(d) >= 2:
            # Handle legacy [title, completed] format
            formatted.append({
                "title": d[0], 
                "completed": d[1], 
                "completedAt": datetime.utcnow().isoformat() if d[1] else None
            })
        elif isinstance(d, dict):
            # Already in new format or partial
            formatted.append({
                "title": d.get("title", ""),
                "completed": d.get("completed", False),
                "completedAt": d.get("completedAt")
            })
    return formatted


def normalize_task(task: Task) -> Task:
    """Ensures task JSON fields use the standard API shape before returning them."""
    task.deliverables = format_deliverables(task.deliverables)
    task.links = task.links or []
    return task


@app.get("/")
def read_root():
    return {"message": "Roadmap API is alive!"}


@app.post("/generate-plan")
def generate_plan(
    onboarding_data: dict, 
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    print(f"Generating plan for user: {user_id}")
    """
    1. Generates tasks using LangChain
    2. Saves a new Roadmap and its Tasks to the database
    3. Returns the generated plan
    """
    ensure_kb_available("Roadmap generation")
    try:
        # Check if user exists in DB
        user = session.exec(select(User).where(User.id == user_id)).first()
        if not user:
            # Safety net: create user with unique placeholder email
            user = User(id=user_id, email=f"{user_id}@placeholder.local", onboarded=True)
            session.add(user)
            session.commit()

        # Generate tasks
        tasks_data = generate_roadmap_tasks(onboarding_data, knowledge_base=kb)
        
        # Create Roadmap
        target_role = onboarding_data.get('targetRole', 'Custom')
        if target_role == "Other":
            target_role = onboarding_data.get('otherRole', 'Custom')
            
        roadmap_id = str(uuid.uuid4())
        roadmap = Roadmap(
            id=roadmap_id,
            title=f"{target_role} Roadmap",
            description="Personalized roadmap generated by AI based on your onboarding.",
            userId=user_id
        )
        session.add(roadmap)
        
        # Create Tasks
        for t in tasks_data:
            task = Task(
                id=str(uuid.uuid4()),
                title=t['title'],
                description=t['description'],
                duration=t['duration'],
                type=t['type'],
                order=t['order'],
                deliverables=format_deliverables(t.get('deliverables', [])),
                links=t.get('links', []),
                roadmapId=roadmap_id
            )
            session.add(task)
        
        session.commit()
        return {"message": "Plan generated successfully", "roadmap_id": roadmap_id}
    except Exception as e:
        print(f"Error generating plan: {e}")
        raise HTTPException(status_code=500, detail="Failed to generate plan")


@app.post("/roadmaps/{roadmap_id}/regenerate")
def regenerate_plan(
    roadmap_id: str,
    payload: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """
    Takes an existing roadmap ID, optional dashboard data, and a regenerate prompt.
    Uses the LLM to rewrite the tasks. Deletes old tasks and returns the new ones.
    """
    feedback = payload.get("feedback", "")
    existing_dashboard = payload.get("dashboard", {})

    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")

    ensure_kb_available("Roadmap regeneration")
    try:
        # Generate new tasks based on existing dashboard and feedback
        # Pass feedback as user_dislikes to the generator
        tasks_data = regenerate_roadmap_tasks(existing_dashboard, feedback, knowledge_base=kb)
        
        # Delete old tasks
        old_tasks = session.exec(select(Task).where(Task.roadmapId == roadmap_id)).all()
        for t in old_tasks:
            session.delete(t)
            
        # Create new Tasks
        for t in tasks_data:
            task = Task(
                id=str(uuid.uuid4()),
                title=t['title'],
                description=t['description'],
                duration=t['duration'],
                type=t['type'],
                order=t['order'],
                deliverables=format_deliverables(t.get('deliverables', [])),
                links=t.get('links', []),
                roadmapId=roadmap_id
            )
            session.add(task)
        
        session.commit()
        return {"message": "Plan regenerated successfully"}
    except Exception as e:
        print(f"Error regenerating plan: {e}")
        raise HTTPException(status_code=500, detail="Failed to regenerate plan")


@app.get("/me")
def get_me(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Protected: returns current user data. Requires Authorization: Bearer <token>."""
    user = session.exec(select(User).where(User.id == user_id)).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {
        "user_id": user.id,
        "email": user.email,
        "name": user.name,
        "isAdmin": user.isAdmin,
        "onboarded": user.onboarded
    }


@app.get("/roadmaps")
def get_roadmaps(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Fetches all roadmaps belonging to the authenticated user. Returns a list of Roadmap objects."""
    print(f"Fetching roadmaps for user: {user_id}")
    try:
        roadmaps = session.exec(select(Roadmap).where(Roadmap.userId == user_id)).all()
        return roadmaps
    except Exception as e:
        print(f"Error fetching roadmaps: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")

@app.get("/roadmaps/{roadmap_id}")
def get_roadmap_details(
    roadmap_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Fetches full details for a specific roadmap, including its tasks. Expects roadmap_id in URL. Returns dict with roadmap and tasks list."""
    roadmap = session.exec(
        select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)
    ).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    tasks = session.exec(
        select(Task).where(Task.roadmapId == roadmap_id).order_by(Task.order)
    ).all()

    for task in tasks:
        normalize_task(task)
    
    return {"roadmap": roadmap, "tasks": tasks}

@app.get("/roadmaps/{roadmap_id}/tasks/{task_id}")
def get_task_details(
    roadmap_id: str,
    task_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Fetches a specific task's details."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task = session.exec(select(Task).where(Task.id == task_id, Task.roadmapId == roadmap_id)).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    return normalize_task(task)

@app.get("/tracks")
def get_tracks():
    # Keep this for compatibility with existing landing page
    return [
        {"id": 1, "name": "LeetCode Mastery", "icon": "code"},
        {"id": 2, "name": "Project Building", "icon": "rocket"},
        {"id": 3, "name": "System Design", "icon": "layout"},
    ]

@app.get("/curated-roadmaps")
def get_curated_roadmaps():
    """Returns the pre-curated roadmaps from seed data."""
    import os
    seed_path = os.path.join(os.path.dirname(__file__), "seed_data", "curated_roadmaps_enhanced.json")
    try:
        with open(seed_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data
    except Exception as e:
        print(f"Error loading curated roadmaps: {e}")
        raise HTTPException(status_code=500, detail="Could not load curated roadmaps")

@app.post("/roadmaps/fork-curated")
def fork_curated_roadmap(
    payload: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Forks a curated roadmap into the user's personal roadmaps."""
    roadmap_data = payload.get("roadmap")
    if not roadmap_data:
        raise HTTPException(status_code=400, detail="Roadmap data missing")

    try:
        new_roadmap_id = str(uuid.uuid4())
        new_roadmap = Roadmap(
            id=new_roadmap_id,
            title=roadmap_data["roadmap_title"],
            description=roadmap_data.get("description", ""),
            userId=user_id
        )
        session.add(new_roadmap)

        for i, t in enumerate(roadmap_data.get("tasks", [])):
            new_task = Task(
                id=str(uuid.uuid4()),
                title=t["title"],
                description=t.get("description", ""),
                duration=t.get("duration", ""),
                type=t.get("type", "info"),
                order=i,
                deliverables=format_deliverables(t.get("deliverables", [])),
                links=t.get("links", []),
                roadmapId=new_roadmap_id
            )
            session.add(new_task)
        
        session.commit()
        session.refresh(new_roadmap)
        return new_roadmap
    except Exception as e:
        print(f"Error forking roadmap: {e}")
        raise HTTPException(status_code=500, detail="Failed to fork roadmap")

@app.get("/recent-progress")
def get_recent_progress(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """
    Fetches all deliverables and tasks completed by the user in the last 7 days.
    """
    from datetime import timedelta
    
    seven_days_ago = datetime.utcnow() - timedelta(days=7)
    
    # 1. Fetch all roadmaps for the user to get context
    roadmaps = session.exec(select(Roadmap).where(Roadmap.userId == user_id)).all()
    roadmap_map = {r.id: r.title for r in roadmaps}
    roadmap_ids = list(roadmap_map.keys())
    
    if not roadmap_ids:
        return []
    
    # 2. Fetch all tasks for these roadmaps
    tasks = session.exec(select(Task).where(Task.roadmapId.in_(roadmap_ids))).all()
    
    achievements = []
    
    for task in tasks:
        # Check if task itself was completed recently
        if task.completedAt and task.completedAt >= seven_days_ago:
            achievements.append({
                "id": task.id,
                "type": "task",
                "title": task.title,
                "roadmapTitle": roadmap_map.get(task.roadmapId),
                "completedAt": task.completedAt.isoformat()
            })
            
        # Check deliverables
        deliverables = task.deliverables or []
        for d in deliverables:
            if isinstance(d, dict):
                comp_at_str = d.get("completedAt")
                if d.get("completed") and comp_at_str:
                    try:
                        comp_at = datetime.fromisoformat(comp_at_str)
                        # Remove timezone if present for comparison
                        if comp_at.tzinfo:
                            comp_at = comp_at.replace(tzinfo=None)
                            
                        if comp_at >= seven_days_ago:
                            achievements.append({
                                "id": f"{task.id}-deliverable-{d.get('title')}",
                                "type": "deliverable",
                                "title": d.get("title"),
                                "taskTitle": task.title,
                                "roadmapTitle": roadmap_map.get(task.roadmapId),
                                "completedAt": comp_at_str
                            })
                    except (ValueError, TypeError):
                        continue
    
    # Sort by date descending
    achievements.sort(key=lambda x: x["completedAt"], reverse=True)
    
    return achievements

# --- Deadline CRUD ---

@app.get("/deadlines")
def get_deadlines(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    try:
        deadlines = session.exec(select(Deadline).where(Deadline.userId == user_id)).all()
        return deadlines
    except Exception as e:
        print(f"Error fetching deadlines: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")

@app.post("/deadlines")
def create_deadline(
    deadline_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    try:
        new_id = str(uuid.uuid4())
        # Convert targetDate string to datetime
        target_date = datetime.fromisoformat(deadline_data["targetDate"].replace('Z', '+00:00'))
        
        deadline = Deadline(
            id=new_id,
            title=deadline_data["title"],
            description=deadline_data.get("description"),
            targetDate=target_date,
            type=deadline_data.get("type", "general"),
            roadmapId=deadline_data.get("roadmapId"),
            taskId=deadline_data.get("taskId"),
            deliverableId=deadline_data.get("deliverableId"),
            userId=user_id
        )
        session.add(deadline)
        session.commit()
        session.refresh(deadline)
        return deadline
    except Exception as e:
        print(f"Error creating deadline: {e}")
        raise HTTPException(status_code=500, detail="Failed to create deadline")

@app.patch("/deadlines/{deadline_id}")
def update_deadline(
    deadline_id: str,
    deadline_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    deadline = session.exec(select(Deadline).where(Deadline.id == deadline_id, Deadline.userId == user_id)).first()
    if not deadline:
        raise HTTPException(status_code=404, detail="Deadline not found")
    
    try:
        if "title" in deadline_data:
            deadline.title = deadline_data["title"]
        if "description" in deadline_data:
            deadline.description = deadline_data["description"]
        if "targetDate" in deadline_data:
            deadline.targetDate = datetime.fromisoformat(deadline_data["targetDate"].replace('Z', '+00:00'))
        if "status" in deadline_data:
            deadline.status = deadline_data["status"]
            
        session.add(deadline)
        session.commit()
        session.refresh(deadline)
        return deadline
    except Exception as e:
        print(f"Error updating deadline: {e}")
        raise HTTPException(status_code=500, detail="Failed to update deadline")

@app.delete("/deadlines/{deadline_id}")
def delete_deadline(
    deadline_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    deadline = session.exec(select(Deadline).where(Deadline.id == deadline_id, Deadline.userId == user_id)).first()
    if not deadline:
        raise HTTPException(status_code=404, detail="Deadline not found")
        
    session.delete(deadline)
    session.commit()
    return {"message": "Deadline deleted"}

# --- Roadmap & Task CRUD ---

@app.post("/roadmaps")
def create_roadmap(
    roadmap_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Creates a new empty roadmap. Expects title and optional description in JSON body. Returns the created Roadmap object."""
    """ Does not check if roadmap with same title already exists."""
    """ Does not add any tasks to the roadmap."""
    roadmap_id = str(uuid.uuid4())
    roadmap = Roadmap(
        id=roadmap_id,
        title=roadmap_data.get("title", "New Roadmap"),
        description=roadmap_data.get("description", ""),
        userId=user_id
    )
    session.add(roadmap)
    session.commit()
    session.refresh(roadmap)
    return roadmap

@app.patch("/roadmaps/{roadmap_id}")
def update_roadmap(
    roadmap_id: str,
    roadmap_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Updates roadmap title or description. Expects roadmap_id in URL and update fields in JSON body. Returns updated Roadmap object."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
    
    if "title" in roadmap_data:
        roadmap.title = roadmap_data["title"]
    if "description" in roadmap_data:
        roadmap.description = roadmap_data["description"]
    
    session.add(roadmap)
    session.commit()
    session.refresh(roadmap)
    return roadmap

@app.delete("/roadmaps/{roadmap_id}")
def delete_roadmap(
    roadmap_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Deletes a roadmap and all its associated tasks. Expects roadmap_id in URL. Returns success message."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
    
    # Delete associated tasks first
    tasks = session.exec(select(Task).where(Task.roadmapId == roadmap_id)).all()
    for task in tasks:
        session.delete(task)
        
    session.delete(roadmap)
    session.commit()
    return {"message": "Roadmap deleted"}

@app.post("/roadmaps/{roadmap_id}/tasks")
def add_task(
    roadmap_id: str,
    task_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Adds a new task to a roadmap. Expects roadmap_id in URL and task details in JSON body. returns the created Task object."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
    
    # Get max order to append
    tasks = session.exec(select(Task).where(Task.roadmapId == roadmap_id)).all()
    next_order = max([t.order for t in tasks], default=-1) + 1
    
    new_task = Task(
        id=str(uuid.uuid4()),
        title=task_data.get("title", "New Task"),
        description=task_data.get("description", ""),
        duration=task_data.get("duration", ""),
        type=task_data.get("type", "info"),
        deliverables=format_deliverables(task_data.get("deliverables", None)),
        links=task_data.get("links", None),
        order=next_order,
        roadmapId=roadmap_id
    )
    session.add(new_task)
    session.commit()
    session.refresh(new_task)
    return new_task

@app.patch("/roadmaps/{roadmap_id}/edit-task/{task_id}")
def update_task(
    roadmap_id: str,
    task_id: str,
    task_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Updates specific task details. Expects roadmap_id and task_id in URL, and update fields in JSON body. Returns updated Task object."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task = session.exec(select(Task).where(Task.id == task_id, Task.roadmapId == roadmap_id)).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    
    if "title" in task_data:
        task.title = task_data["title"]
    if "description" in task_data:
        task.description = task_data["description"]
    if "duration" in task_data:
        task.duration = task_data["duration"]
    if "type" in task_data:
        task.type = task_data["type"]
    if "status" in task_data:
        task.status = task_data["status"]
        if task.status == "completed" and not task.completedAt:
            task.completedAt = datetime.utcnow()
        elif task.status != "completed":
            task.completedAt = None

    if "deliverables" in task_data:
        old_deliverables = task.deliverables or []
        new_deliverables_raw = task_data["deliverables"]
        
        # Handle stringified JSON from frontend
        if isinstance(new_deliverables_raw, str):
            try:
                new_deliverables = json.loads(new_deliverables_raw)
            except:
                new_deliverables = []
        else:
            new_deliverables = new_deliverables_raw
            
        if not isinstance(new_deliverables, list):
            new_deliverables = []

        # We need to preserve completion dates if they exist, 
        # or set them if newly completed.
        final_deliverables = []
        for i, new_d in enumerate(new_deliverables):
            # Ensure new_d is a dict (frontend might still send strings)
            if isinstance(new_d, str):
                new_d = {"title": new_d, "completed": False}
            elif isinstance(new_d, (list, tuple)):
                new_d = {"title": new_d[0], "completed": new_d[1]}
            
            # Find matching old deliverable to check for status change
            # Default to checking by index, but ideally by title if possible?
            # For now, index is safer for simple lists.
            old_d = old_deliverables[i] if i < len(old_deliverables) else None
            
            title = new_d.get("title", "")
            completed = new_d.get("completed", False)
            completed_at = new_d.get("completedAt")
            
            if old_d:
                # If it was a legacy tuple, convert it
                if isinstance(old_d, (list, tuple)):
                    old_d = {"title": old_d[0], "completed": old_d[1], "completedAt": None}
                
                # If status changed to completed, set timestamp
                if completed and not old_d.get("completed"):
                    completed_at = datetime.utcnow().isoformat()
                elif not completed:
                    completed_at = None
                else:
                    # Keep existing timestamp if it was already completed
                    completed_at = old_d.get("completedAt") or completed_at
            elif completed and not completed_at:
                completed_at = datetime.utcnow().isoformat()
                
            final_deliverables.append({
                "title": title,
                "completed": completed,
                "completedAt": completed_at
            })
            
        task.deliverables = final_deliverables
        
        # Check if all deliverables are completed to auto-complete the task
        if final_deliverables:
            all_done = all(d.get("completed") for d in final_deliverables)
            if all_done:
                task.status = "completed"
                if not task.completedAt:
                    task.completedAt = datetime.utcnow()
            else:
                # If any are NOT completed, task is NOT completed
                if task.status == "completed":
                    task.status = "in_progress"
                task.completedAt = None

    if "links" in task_data:
        task.links = task_data["links"]
    if "order" in task_data:
        task.order = task_data["order"]
        
    session.add(task)
    session.commit()
    session.refresh(task)
    return task

@app.delete("/roadmaps/{roadmap_id}/delete-task/{task_id}")
def delete_task(
    roadmap_id: str,
    task_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Deletes a specific task from a roadmap. Expects roadmap_id and task_id in URL. Returns success message."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task = session.exec(select(Task).where(Task.id == task_id, Task.roadmapId == roadmap_id)).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
        
    session.delete(task)
    session.commit()
    return {"message": "Task deleted"}

@app.patch("/roadmaps/{roadmap_id}/reorder-tasks")
def reorder_tasks(
    roadmap_id: str,
    order_data: dict, # Expecting {"task_ids": [id1, id2, ...]}
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Updates the 'order' field for multiple tasks based on the provided list of IDs. Expects roadmap_id in URL and task_ids list in body. Returns success message."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task_ids = order_data.get("task_ids", [])
    for index, tid in enumerate(task_ids):
        task = session.exec(select(Task).where(Task.id == tid, Task.roadmapId == roadmap_id)).first()
        if task:
            task.order = index
            session.add(task)
    
    session.commit()
    return {"message": "Order updated"}

# --- Admin & RAG Management ---

@app.get("/admin/rag/stats")
def get_rag_stats(admin: User = Depends(get_current_admin)):
    """Protected: returns RAG pipeline statistics."""
    return kb.get_stats()

@app.post("/admin/rag/ingest")
def ingest_knowledge(admin: User = Depends(get_current_admin)):
    """Protected: triggers knowledge document ingestion."""
    ensure_kb_available("Knowledge ingestion")
    kb.ingest_knowledge_docs()
    return {"message": "Knowledge document ingestion triggered successfully"}

@app.post("/admin/rag/query")
def query_rag(
    payload: dict,
    admin: User = Depends(get_current_admin)
):
    """Protected: runs a retrieval-only query against the knowledge base."""
    ensure_kb_available("Retrieval playground")

    query_text = (payload.get("query") or "").strip()
    top_k = payload.get("top_k", 5)

    if not query_text:
        raise HTTPException(status_code=400, detail="Query text is required")

    try:
        top_k = int(top_k)
    except (TypeError, ValueError):
        raise HTTPException(status_code=400, detail="top_k must be an integer")

    top_k = max(1, min(top_k, 10))

    try:
        results = kb.query(query_text, top_k=top_k)
        return {
            "query": query_text,
            "top_k": top_k,
            "results": results,
        }
    except Exception as e:
        print(f"Error querying knowledge base: {e}")
        raise HTTPException(status_code=500, detail="Failed to query knowledge base")

@app.get("/admin/feedback")
def get_feedback_logs(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """
    Fetches all regeneration feedback logs.
    Currently, we will just fetch recent Roadmap updates that came from regeneration.
    (In Phase 2 we will use a proper FeedbackLog table)
    """
    # For now, let's just return a placeholder or query roadmaps with specific feedback
    return {"message": "Feedback monitoring coming soon in Phase 2 with FeedbackLog table"}
