from fastapi import Depends, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlmodel import Session, select
import uuid
from dotenv import load_dotenv

# Load environment variables early
load_dotenv()

from datetime import datetime
from auth import get_user_id
from database import engine, Roadmap, Task, User, Deadline, get_session
from generator import generate_roadmap_tasks, regenerate_roadmap_tasks
import json

app = FastAPI()

# Allow frontend to talk to backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",  # Next.js dev
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def read_root():
    return {"message": "Roadmap API is alive!"}


@app.post("/generate-plan")
def generate_plan(
    onboarding_data: dict, 
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    print(f"Generating plan for user: {user_id}")
    """
    1. Generates tasks using LangChain
    2. Saves a new Roadmap and its Tasks to the database
    3. Returns the generated plan
    """
    try:
        # Check if user exists in DB
        user = session.exec(select(User).where(User.id == user_id)).first()
        if not user:
            user = User(id=user_id, email="", onboarded=True)
            session.add(user)
            session.commit()

        # Generate tasks
        tasks_data = generate_roadmap_tasks(onboarding_data)
        
        # Create Roadmap
        target_role = onboarding_data.get('targetRole', 'Custom')
        if target_role == "Other":
            target_role = onboarding_data.get('otherRole', 'Custom')
            
        roadmap_id = str(uuid.uuid4())
        roadmap = Roadmap(
            id=roadmap_id,
            title=f"{target_role} Roadmap",
            description="Personalized roadmap generated by AI based on your onboarding.",
            userId=user_id
        )
        session.add(roadmap)
        
        # Create Tasks
        for t in tasks_data:
            task = Task(
                id=str(uuid.uuid4()),
                title=t['title'],
                description=t['description'],
                duration=t['duration'],
                type=t['type'],
                order=t['order'],
                deliverables=t.get('deliverables', []),
                links=t.get('links', []),
                roadmapId=roadmap_id
            )
            session.add(task)
        
        session.commit()
        return {"message": "Plan generated successfully", "roadmap_id": roadmap_id}
    except Exception as e:
        print(f"Error generating plan: {e}")
        raise HTTPException(status_code=500, detail="Failed to generate plan")


@app.post("/roadmaps/{roadmap_id}/regenerate")
def regenerate_plan(
    roadmap_id: str,
    payload: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """
    Takes an existing roadmap ID, optional dashboard data, and a regenerate prompt.
    Uses the LLM to rewrite the tasks. Deletes old tasks and returns the new ones.
    """
    feedback = payload.get("feedback", "")
    existing_dashboard = payload.get("dashboard", {})

    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")

    try:
        # Generate new tasks based on existing dashboard and feedback
        tasks_data = regenerate_roadmap_tasks(existing_dashboard, feedback)
        
        # Delete old tasks
        old_tasks = session.exec(select(Task).where(Task.roadmapId == roadmap_id)).all()
        for t in old_tasks:
            session.delete(t)
            
        # Create new Tasks
        for t in tasks_data:
            task = Task(
                id=str(uuid.uuid4()),
                title=t['title'],
                description=t['description'],
                duration=t['duration'],
                type=t['type'],
                order=t['order'],
                deliverables=t.get('deliverables', []),
                links=t.get('links', []),
                roadmapId=roadmap_id
            )
            session.add(task)
        
        session.commit()
        return {"message": "Plan regenerated successfully"}
    except Exception as e:
        print(f"Error regenerating plan: {e}")
        raise HTTPException(status_code=500, detail="Failed to regenerate plan")


@app.get("/me")
def get_me(user_id: str = Depends(get_user_id)):
    """Protected: returns current user id from JWT. Requires Authorization: Bearer <token>."""
    return {"user_id": user_id}


@app.get("/roadmaps")
def get_roadmaps(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Fetches all roadmaps belonging to the authenticated user. Returns a list of Roadmap objects."""
    print(f"Fetching roadmaps for user: {user_id}")
    try:
        roadmaps = session.exec(select(Roadmap).where(Roadmap.userId == user_id)).all()
        return roadmaps
    except Exception as e:
        print(f"Error fetching roadmaps: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")

@app.get("/roadmaps/{roadmap_id}")
def get_roadmap_details(
    roadmap_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Fetches full details for a specific roadmap, including its tasks. Expects roadmap_id in URL. Returns dict with roadmap and tasks list."""
    roadmap = session.exec(
        select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)
    ).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    tasks = session.exec(
        select(Task).where(Task.roadmapId == roadmap_id).order_by(Task.order)
    ).all()
    
    return {"roadmap": roadmap, "tasks": tasks}

@app.get("/roadmaps/{roadmap_id}/tasks/{task_id}")
def get_task_details(
    roadmap_id: str,
    task_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Fetches a specific task's details."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task = session.exec(select(Task).where(Task.id == task_id, Task.roadmapId == roadmap_id)).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
        
    return task

@app.get("/tracks")
def get_tracks():
    # Keep this for compatibility with existing landing page
    return [
        {"id": 1, "name": "LeetCode Mastery", "icon": "code"},
        {"id": 2, "name": "Project Building", "icon": "rocket"},
        {"id": 3, "name": "System Design", "icon": "layout"},
    ]

@app.get("/curated-roadmaps")
def get_curated_roadmaps():
    """Returns the pre-curated roadmaps from seed data."""
    import os
    seed_path = os.path.join(os.path.dirname(__file__), "seed_data", "curated_roadmaps_enhanced.json")
    try:
        with open(seed_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data
    except Exception as e:
        print(f"Error loading curated roadmaps: {e}")
        raise HTTPException(status_code=500, detail="Could not load curated roadmaps")

@app.post("/roadmaps/fork-curated")
def fork_curated_roadmap(
    payload: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Forks a curated roadmap into the user's personal roadmaps."""
    roadmap_data = payload.get("roadmap")
    if not roadmap_data:
        raise HTTPException(status_code=400, detail="Roadmap data missing")

    try:
        new_roadmap_id = str(uuid.uuid4())
        new_roadmap = Roadmap(
            id=new_roadmap_id,
            title=roadmap_data["roadmap_title"],
            description=roadmap_data.get("description", ""),
            userId=user_id
        )
        session.add(new_roadmap)

        for i, t in enumerate(roadmap_data.get("tasks", [])):
            new_task = Task(
                id=str(uuid.uuid4()),
                title=t["title"],
                description=t.get("description", ""),
                duration=t.get("duration", ""),
                type=t.get("type", "info"),
                order=i,
                deliverables=t.get("deliverables", []),
                links=t.get("links", []),
                roadmapId=new_roadmap_id
            )
            session.add(new_task)
        
        session.commit()
        session.refresh(new_roadmap)
        return new_roadmap
    except Exception as e:
        print(f"Error forking roadmap: {e}")
        raise HTTPException(status_code=500, detail="Failed to fork roadmap")

# --- Deadline CRUD ---

@app.get("/deadlines")
def get_deadlines(
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    try:
        deadlines = session.exec(select(Deadline).where(Deadline.userId == user_id)).all()
        return deadlines
    except Exception as e:
        print(f"Error fetching deadlines: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")

@app.post("/deadlines")
def create_deadline(
    deadline_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    try:
        new_id = str(uuid.uuid4())
        # Convert targetDate string to datetime
        target_date = datetime.fromisoformat(deadline_data["targetDate"].replace('Z', '+00:00'))
        
        deadline = Deadline(
            id=new_id,
            title=deadline_data["title"],
            description=deadline_data.get("description"),
            targetDate=target_date,
            type=deadline_data.get("type", "general"),
            roadmapId=deadline_data.get("roadmapId"),
            taskId=deadline_data.get("taskId"),
            deliverableId=deadline_data.get("deliverableId"),
            userId=user_id
        )
        session.add(deadline)
        session.commit()
        session.refresh(deadline)
        return deadline
    except Exception as e:
        print(f"Error creating deadline: {e}")
        raise HTTPException(status_code=500, detail="Failed to create deadline")

@app.patch("/deadlines/{deadline_id}")
def update_deadline(
    deadline_id: str,
    deadline_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    deadline = session.exec(select(Deadline).where(Deadline.id == deadline_id, Deadline.userId == user_id)).first()
    if not deadline:
        raise HTTPException(status_code=404, detail="Deadline not found")
    
    try:
        if "title" in deadline_data:
            deadline.title = deadline_data["title"]
        if "description" in deadline_data:
            deadline.description = deadline_data["description"]
        if "targetDate" in deadline_data:
            deadline.targetDate = datetime.fromisoformat(deadline_data["targetDate"].replace('Z', '+00:00'))
        if "status" in deadline_data:
            deadline.status = deadline_data["status"]
            
        session.add(deadline)
        session.commit()
        session.refresh(deadline)
        return deadline
    except Exception as e:
        print(f"Error updating deadline: {e}")
        raise HTTPException(status_code=500, detail="Failed to update deadline")

@app.delete("/deadlines/{deadline_id}")
def delete_deadline(
    deadline_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    deadline = session.exec(select(Deadline).where(Deadline.id == deadline_id, Deadline.userId == user_id)).first()
    if not deadline:
        raise HTTPException(status_code=404, detail="Deadline not found")
        
    session.delete(deadline)
    session.commit()
    return {"message": "Deadline deleted"}

# --- Roadmap & Task CRUD ---

@app.post("/roadmaps")
def create_roadmap(
    roadmap_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Creates a new empty roadmap. Expects title and optional description in JSON body. Returns the created Roadmap object."""
    """ Does not check if roadmap with same title already exists."""
    """ Does not add any tasks to the roadmap."""
    roadmap_id = str(uuid.uuid4())
    roadmap = Roadmap(
        id=roadmap_id,
        title=roadmap_data.get("title", "New Roadmap"),
        description=roadmap_data.get("description", ""),
        userId=user_id
    )
    session.add(roadmap)
    session.commit()
    session.refresh(roadmap)
    return roadmap

@app.patch("/roadmaps/{roadmap_id}")
def update_roadmap(
    roadmap_id: str,
    roadmap_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Updates roadmap title or description. Expects roadmap_id in URL and update fields in JSON body. Returns updated Roadmap object."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
    
    if "title" in roadmap_data:
        roadmap.title = roadmap_data["title"]
    if "description" in roadmap_data:
        roadmap.description = roadmap_data["description"]
    
    session.add(roadmap)
    session.commit()
    session.refresh(roadmap)
    return roadmap

@app.delete("/roadmaps/{roadmap_id}")
def delete_roadmap(
    roadmap_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Deletes a roadmap and all its associated tasks. Expects roadmap_id in URL. Returns success message."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
    
    # Delete associated tasks first
    tasks = session.exec(select(Task).where(Task.roadmapId == roadmap_id)).all()
    for task in tasks:
        session.delete(task)
        
    session.delete(roadmap)
    session.commit()
    return {"message": "Roadmap deleted"}

@app.post("/roadmaps/{roadmap_id}/tasks")
def add_task(
    roadmap_id: str,
    task_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Adds a new task to a roadmap. Expects roadmap_id in URL and task details in JSON body. returns the created Task object."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
    
    # Get max order to append
    tasks = session.exec(select(Task).where(Task.roadmapId == roadmap_id)).all()
    next_order = max([t.order for t in tasks], default=-1) + 1
    
    new_task = Task(
        id=str(uuid.uuid4()),
        title=task_data.get("title", "New Task"),
        description=task_data.get("description", ""),
        duration=task_data.get("duration", ""),
        type=task_data.get("type", "info"),
        deliverables=task_data.get("deliverables", None),
        links=task_data.get("links", None),
        order=next_order,
        roadmapId=roadmap_id
    )
    session.add(new_task)
    session.commit()
    session.refresh(new_task)
    return new_task

@app.patch("/roadmaps/{roadmap_id}/edit-task/{task_id}")
def update_task(
    roadmap_id: str,
    task_id: str,
    task_data: dict,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Updates specific task details. Expects roadmap_id and task_id in URL, and update fields in JSON body. Returns updated Task object."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task = session.exec(select(Task).where(Task.id == task_id, Task.roadmapId == roadmap_id)).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    
    if "title" in task_data:
        task.title = task_data["title"]
    if "description" in task_data:
        task.description = task_data["description"]
    if "duration" in task_data:
        task.duration = task_data["duration"]
    if "type" in task_data:
        task.type = task_data["type"]
    if "status" in task_data:
        task.status = task_data["status"]
    if "deliverables" in task_data:
        task.deliverables = task_data["deliverables"]
    if "links" in task_data:
        task.links = task_data["links"]
    if "order" in task_data:
        task.order = task_data["order"]
        
    session.add(task)
    session.commit()
    session.refresh(task)
    return task

@app.delete("/roadmaps/{roadmap_id}/delete-task/{task_id}")
def delete_task(
    roadmap_id: str,
    task_id: str,
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Deletes a specific task from a roadmap. Expects roadmap_id and task_id in URL. Returns success message."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task = session.exec(select(Task).where(Task.id == task_id, Task.roadmapId == roadmap_id)).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
        
    session.delete(task)
    session.commit()
    return {"message": "Task deleted"}

@app.patch("/roadmaps/{roadmap_id}/reorder-tasks")
def reorder_tasks(
    roadmap_id: str,
    order_data: dict, # Expecting {"task_ids": [id1, id2, ...]}
    user_id: str = Depends(get_user_id),
    session: Session = Depends(get_session)
):
    """Updates the 'order' field for multiple tasks based on the provided list of IDs. Expects roadmap_id in URL and task_ids list in body. Returns success message."""
    roadmap = session.exec(select(Roadmap).where(Roadmap.id == roadmap_id, Roadmap.userId == user_id)).first()
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")
        
    task_ids = order_data.get("task_ids", [])
    for index, tid in enumerate(task_ids):
        task = session.exec(select(Task).where(Task.id == tid, Task.roadmapId == roadmap_id)).first()
        if task:
            task.order = index
            session.add(task)
    
    session.commit()
    return {"message": "Order updated"}